### ISSUE TITLE
小米平板6上竖屏时上下分屏失效

### ISSUE THREAD

**Issue by byf3332** [YifePlayte/MaxMiPad#11]
小米平板国行6标准版非pro8+256G，系统版本miui14.0.10
见图

我的操作流程：

1. 这个开关打开了并且lsp内推荐作用域均勾选
![Screenshot_2024-02-04-22-20-01-502_com yifeplayte maxmipadinput](https://github.com/YifePlayte/MaxMiPad/assets/71202267/60d1c8d9-85e2-4c31-a8db-0077162afae9)

2. 竖屏状态下尝试分屏时也可看到这个按钮变成上下的样式
![Screenshot_2024-02-04-22-20-31-468_com miui home-edit](https://github.com/YifePlayte/MaxMiPad/assets/71202267/df6ba9f4-f3c3-4c0f-8daf-b0d90f25917c)

3. 但是分屏仍然是左右样式
![Screenshot_2024-02-04-22-21-22-409_bin mt plus](https://github.com/YifePlayte/MaxMiPad/assets/71202267/7f1f0a08-b0fa-4b3f-9ad4-8be421de9deb)

4. 这时候进入最近任务又可以看到它变成了上下样式，再点回去还是左右样式
![Screenshot_2024-02-04-22-21-27-357_com miui home](https://github.com/YifePlayte/MaxMiPad/assets/71202267/e3e71313-e5c0-4d1d-a0be-3715f6e18497)

**Comment by YifePlayte** [comment]
抱歉，但此功能目前只针对HyperOS作适配。下个版本会在MIUI上隐藏此开关。
