### ISSUE TITLE
能否模拟小米官方笔蓝牙连接以解除随手写的限制

### ISSUE THREAD

**Issue by ybhgl** [YifePlayte/MaxMiPad#12]
最近测试时候发现平板连接上官方笔蓝牙后，小新灵感触控笔也能使用随手写（就是连上官方笔，打开随手写开关，然后用小新笔也能写字）
可不可以研究一下模拟官方蓝牙连接或者强制开启随手写开关？

**Comment by YifePlayte** [comment]
已解决，但仍旧推荐使用Gboard的手写功能。
