### ISSUE TITLE
请求添加【解除游戏内屏蔽触控笔】的功能

### ISSUE THREAD

**Issue by ybhgl** [YifePlayte/MaxMiPad#13]
目前小米将已经添加至游戏加速内的游戏默认屏蔽触控笔，能否去除该限制

**Comment by YifePlayte** [comment]
未复现，请提供你的设备型号、系统版本等信息。以及请确认你的游戏是否支持触控笔，据我所知有部分游戏本身不支持触控笔操作。

**Comment by ybhgl** [comment]
> 未复现，请提供你的设备型号、系统版本等信息。以及请确认你的游戏是否支持触控笔，据我所知有部分游戏本身不支持触控笔操作。

小米平板5Pro 12.4，澎湃，a14
测试游戏：mini metro
测试步骤：把游戏从游戏加速中移出，可以正常使用触控笔进行游玩。重新添加回游戏加速内，不能使用触控笔。

**Comment by ybhgl** [comment]
> 未复现，请提供你的设备型号、系统版本等信息。以及请确认你的游戏是否支持触控笔，据我所知有部分游戏本身不支持触控笔操作。

找到原因了，在游戏加速内打开触控优化会屏蔽触控笔，关掉就可以正常用了

**Comment by YifePlayte** [comment]
触控优化是内核指令，我无法干预，就算干预也会影响触控优化效果。
