### ISSUE TITLE
光标未正常变化

### ISSUE THREAD

**Issue by Jan-Arbus** [YifePlayte/MaxMiPad#16]
如这个视频所见，光标在脱离拖拽状态后并未恢复到之前的状态。
悬停在可点击物品上时光标也不会变化为“可点击”光标
系统信息：
* 小米平板5Pro5G/HyperOS1.0.1.0
* Apatch0.10.7(10763)/ZygiskNEXT 1.0.5/LSPosed1.9.2

https://github.com/YifePlayte/MaxMiPad/assets/74862110/d08dad40-580b-413c-9e32-701826b52819

**Comment by YifePlayte** [comment]
本模块仅恢复原生鼠标指针，未对指针逻辑做任何修改。请确认你复现此bug的浏览器版本，尝试在其他设备（比如手机）上使用同一版本浏览器是否能够复现此bug，理论上此bug与模块无关。并且，Hyper OS现在自带了切回原生鼠标指针的功能，也请尝试关闭模块内此功能并尝试系统自带的切换样式功能再次测试。（在连接键盘后去系统设置里能够找到指针样式选择，第一个就是原生的，但我之前碰到过此设置偶尔不生效，所以在确认不是模块问题后，个人建议继续使用模块）

**Comment by Jan-Arbus** [comment]
> 并且，Hyper OS现在自带了切回原生鼠标指针的功能

经过检查，键盘设置中调整光标样式的选项只有大圆点与小圆点可选，并无原生光标选项
> 请确认你复现此bug的浏览器版本，尝试在其他设备（比如手机）上使用同一版本浏览器是否能够复现此bug

该Bug与浏览器无关，在系统自带的笔记、短信、WPS中均能复现此BUG
> 尝试在其他设备（比如手机）上使用同一版本浏览器是否能够复现此bug

很不幸，我目前没有小米手机

**Comment by YifePlayte** [comment]
> 经过检查，键盘设置中调整光标样式的选项只有大圆点与小圆点可选，并无原生光标选项

抱歉没有仔细观察视频，您的设备可能是安卓13的HyperOS。

若您有能力，可以尝试关闭本模块的功能，自行制作一个Magisk模块，修改`/system/product/etc/device_features/`下的xml文件，找到`support_magic_pointer`项目修改为false。若这种方案依旧有bug，那么很不幸，我没有什么可以帮到您的了。

**Comment by Jan-Arbus** [comment]
> 自行制作一个Magisk模块，修改/system/product/etc/device_features/下的xml文件，找到support_magic_pointer项目修改为false。

很不幸，该方案并未按照预期工作（禁用Magic Pointer，恢复原生光标）
将会关闭该问题
