### ISSUE TITLE
请问微软的surface pen可以用吗？

### ISSUE THREAD

**Issue by ihanhua** [YifePlayte/MaxMiPad#5]

**Comment by YifePlayte** [comment]
@ihanhua 不支持，所有版本的Surface Pen理论上都不受支持。

**Comment by KohGeek** [comment]
不好意思，这里翻旧贴来问

理论上支持的 external pen 有哪一款？是 AES protocol 的吗？

**Comment by YifePlayte** [comment]
> 不好意思，这里翻旧贴来问
> 
> 理论上支持的 external pen 有哪一款？是 AES protocol 的吗？
> 
> 据我所知，Lenovo Precision Pen 2 是有可能支持的

我对触控笔协议并不了解，也并没有买过第三方触控笔。或许你可以去酷安社区的对应机型话题下寻求帮助。

以及，我可能需要修正之前的回答，貌似有部分surface pen是受支持的，但我不知道具体是哪一代。

**Comment by KohGeek** [comment]
okay 好，谢谢你
